### ISSUE TITLE
Add "OpenJDK" to PyPi description for SEO

### ISSUE THREAD

**Issue by kthejoker** [jyksnw/install-jdk#12]
Minor (but annoying!) issue!

Steps to reproduce:

1) Search PyPi.org for "openjdk."

Expected Behavior

install-jdk somewhere near the top of results.

Actual Behavior

install-jdk not in results at all.

Happily it does show at the top when searching for "JDK" but a little SEO never hurt anyone.

**Comment by jyksnw** [comment]
@kthejoker, I apologize for taking so long to comment on this amazing suggestion. I will be updating the PyPi description shortly to have better SEO and to align with the soon-to-be implementation to move to Adoptium.

**Comment by jyksnw** [comment]
PyPi description updated to add OpenJDK and keywords for the supported build vendors.
