### ISSUE TITLE
Cannot access Adoptium on Mac M2

### ISSUE THREAD

**Issue by buchholzmd** [jyksnw/install-jdk#135]
Hello, I am trying to install `jdk` on my new mac and recieve a 404 error when trying to run `jdk.install('17'))`.

I can run `jdk.install('17', vendor='Azul'))` as well as access that link directly in web browser.

However, for Adoptium, when running `jdk.get_download_url('17')` I get the following link for mac arm, which cannot be accessed from a web browser:
`https://api.adoptium.net/v3/binary/latest/17/ga/mac/arm/jdk/hotspot/normal/eclipse`

However, I changed to this architecture and this url works:
`https://api.adoptium.net/v3/binary/latest/17/ga/mac/aarch64/jdk/hotspot/normal/eclipse`

Any help for quickest way to setup on Mac M2 would be great and thanks in advance

**Comment by buchholzmd** [comment]
Following up on this, I looked at the different Adoptium releases, and there is `aarch64` and `arm` available for the linux releases, and only `aarch64` for the MacOS (arm based, of course) releases. This makes sense to me, but as a side note am confused in the difference between linux 'aarch64' and 'arm' as I thought they were the same architectures.

Still, it seems with the M2, `install-jdk` is generating the url with `arm` as the architecture, and as such the `url` won't exist without one explicitly changing the `url` or including the `arch` parameter.

**Comment by jsnow-taconic** [comment]
As a temporary workaround jdk.install() has a named parameter called arch. You can pass in the architecture of your choice with arch=Architecure.AARCH64. I will need to update the Adoptium architecture detection to account for this.

**Comment by jyksnw** [comment]
@buchholzmd this has been fixed in version 1.1.0
