### ISSUE TITLE
test.pypi.org project name

### ISSUE THREAD

**Issue by jyksnw** [jyksnw/install-jdk#35]
@Robbie-Palmer, I am revamping this library and see that you have claimed the install-jdk project on test.pypi.org. Can you release that project name by deleting your copy so I can get a proper release pipeline setup?

**Comment by Robbie-Palmer** [comment]
Ah apologies @jyksnw, I've now deleted this project

**Comment by jyksnw** [comment]
@Robbie-Palmer awesome! Thanks for the quick response.
