### ISSUE TITLE
Put java dir path in "PATH" environment variable

### ISSUE THREAD

**Issue by Maskgirl** [jyksnw/install-jdk#4]

**Comment by Maskgirl** [comment]
@jyksnw sir, please add label 'hacktoberfest'

**Comment by Maskgirl** [comment]
it seems impossible in the case of windows 
i believe that can be possible if we somehow download .exe installer and open it with python script so, user can install java jdk

**Comment by jyksnw** [comment]
Hi @Maskgirl  thanks for raising this issue.

It is not the intention of this utility script to update the PATH. That decision is left up to the user on how they wish to use the downloaded JDK/JRE including if they wish to add it to their PATH.
