### ISSUE TITLE
Does install-jdk support Python 3.8?

### ISSUE THREAD

**Issue by hx2A** [jyksnw/install-jdk#83]
I'm told that `import jdk` raises a "TypeError: 'type' object is not subscriptable" exception in Python 3.8, and that this is a Python 3.8 issue. Did you drop support for Python 3.8? Your pyproject.toml file mentions Python 3.8 and the [pypi](https://pypi.org/project/install-jdk/) page says 3.8 in the requirements section but lists 3.9 in the classifiers. Also, your readme has a Python 3.9-3.11 badge. If you don't support Python 3.8 anymore, that's fine, I can update my documentation to make that clear, but it would be helpful if pypi's requirements were for >= 3.9 so users couldn't install it on 3.8.

Thanks!

**Comment by jyksnw** [comment]
Hi @hx2A, I will need to look into this and get back to you. The library itself should be compatible with 3.6 and newer but I have had to upgrade the version support to 3.8.1 for some of the development dependencies. Do you you have any additional details on the error?

**Comment by hx2A** [comment]
Hi @jyksnw , this originated in a [discussion thread](https://github.com/py5coding/py5generator/discussions/262) in py5generator, as reported by @Maltiec. @Maltiec, can you provide additional information so we can fix this?

**Comment by Maltiec** [comment]
(py5coding_test) evgeniy@DigitalTrinity:~$ python --version
Python 3.8.16
(py5coding_test) evgeniy@DigitalTrinity:~$ pip install install-jdk
Collecting install-jdk
  Downloading install_jdk-1.0.2-py3-none-any.whl (15 kB)
Installing collected packages: install-jdk
Successfully installed install-jdk-1.0.2
(py5coding_test) evgeniy@DigitalTrinity:~$ python -c "import jdk"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/evgeniy/anaconda3/envs/py5coding_test/lib/python3.8/site-packages/jdk/__init__.py", line 10, in <module>
    from jdk.client import load_client
  File "/home/evgeniy/anaconda3/envs/py5coding_test/lib/python3.8/site-packages/jdk/client/__init__.py", line 1, in <module>
    from jdk.client.adoptium import AdoptiumClient
  File "/home/evgeniy/anaconda3/envs/py5coding_test/lib/python3.8/site-packages/jdk/client/adoptium.py", line 3, in <module>
    from jdk.enums import Architecture
  File "/home/evgeniy/anaconda3/envs/py5coding_test/lib/python3.8/site-packages/jdk/enums.py", line 6, in <module>
    class BaseEnum(str, Enum):
  File "/home/evgeniy/anaconda3/envs/py5coding_test/lib/python3.8/site-packages/jdk/enums.py", line 7, in BaseEnum
    def __contains__(self: type[Enum], obj: object) -> bool:
TypeError: 'type' object is not subscriptable

**Comment by jyksnw** [comment]
Thanks @Maltiec that is super helpful. It looks like the type hinting on that method is causing the issues. I will get that corrected and a new release pushed out this week.

**Comment by jyksnw** [comment]
I just released 1.0.4 which resolves this issue. I am also going to open a new issue to set up something like nox along with some unit/sanity tests to test against versions 3.6+ and hopefully capture these failures before they hit release.

**Comment by hx2A** [comment]
Thank you, and that sounds like a great plan.
